### ISSUE TITLE
more than 0 value to unpack - gen_anchors.py

### ISSUE THREAD

**Issue by VanitarNordic** [Jumabek/darknet_scripts#7]
Hi,

I get the following error when I try to execute `gen_anchors.py `

```
Traceback (most recent call last):
  File "gen_anchors.py", line 165, in <module>
    main(sys.argv)
  File "gen_anchors.py", line 142, in main
    w,h = line.split(' ')[3:]
ValueError: need more than 0 values to unpack
```

I run the code in Windows

**Comment by VanitarNordic** [comment]
I don't use original voc. I have a custom dataset with two `.txt` files, `train.txt` and `val.txt` which hold paths, which point to the training/validation images. 

images are annotated in YOLO format with the same name as images (for example `a.jpg` and `a.txt`) and are placed in the same folder as their corresponding images saved. like this

/train

- 0.jpg
- 0.txt
- 1.jpg
- 1.txt

/val

- a.jpg
- a.txt
- b.jpg
- b.txt

**Comment by Jumabek** [comment]
Hi,
Could you try Steven's solution here, I think you have a trailing whitespace in your label files.
https://github.com/Jumabek/darknet_scripts/issues/1

If it doesn;t work, please share your sample annotations here. I want to know if they are in the correct format.

**Comment by VanitarNordic** [comment]
The annotations are created in Windows, this is s sample annotation: 

`0 0.479297 0.554861 0.705469 0.793056`

if you mean by the training-white space, there is an empty line with no character after the last annotation (\n). Do you mean this?

```
0 0.479297 0.554861 0.705469 0.793056
<empty-line-with-no-character-space>
```

**Comment by VanitarNordic** [comment]
Alright, the issue is resolved. The problem was that I had some background-only images also in the database which naturally have no annotation inside txt files and therefore no anchor. I removed them for calculation and now the code works.
